WIDTH = 400
HEIGHT = 300
PLAYERWIDTH = 64
OBSTACLEWIDTH = 30
PRESENTWIDTH = 100
PRESENTHEIGHT = 75
OBJECT_SPEED = 0.3
OBJECTSHOR = 1
OBJECTSVER = 1

SPLIT = [0,
         2,
         4,
         4 + OBJECTSHOR,
         4 + OBJECTSHOR * 2,
         4 + OBJECTSHOR * 2 + OBJECTSVER,
         4 + OBJECTSHOR * 2 + OBJECTSVER * 2]
OBS_SIZE = 4 + OBJECTSHOR * 2 + OBJECTSVER * 2 + 2
REWARD_TYPES = 2
ACTION_SIZE = 2
