WIDTH = 400
HEIGHT = 300
PLAYERWIDTH = 64
PRESENTWIDTH = 100
PRESENTHEIGHT = 75
PLAYERSPEED = 0.3
ACT_DRAW_LENGTH = 60
ACT_GRAD_LENGTH = 10

OBS_SIZE = 4
REWARD_TYPES = 1
ACTION_SIZE = 2

DATASET_SPLIT = (OBS_SIZE, ACTION_SIZE, OBS_SIZE, REWARD_TYPES)
